const EDITOR_ELEMENT_IDS = [
  "projectTabs", "projectTabsList", "projectTabAdd", "toolbarMain", "overflowGroup", "toolbarOverflowToggle", "toolbarOverflowPopup",
  "projectName", "projectNamePanel", "saveIndicator", "languageToggle", "themeToggle", "themeIcon", "themePopup", "helpOpen", "viewModeArt", "viewModeInstall", "viewModeSpec",
  "mobileMenu", "installApp", "installBanner", "installBannerText", "installBannerAction", "installBannerClose",
  "helpModal", "helpClose", "projectLinkModal", "projectLinkQr", "projectLinkLoading", "projectLinkText", "projectLinkCopyBtn",
  "sidePanel", "sideClose", "multiEditBadge",
  "mDockToggle", "mToolSelect", "mToolDraw", "mToolNote", "mToolMaskAdd", "mToolCellEdit", "mToolFlowEdit", "mToolClusterEdit", "mToolRigEdit", "mLockAllToggle",
  "mCopy", "mCopyMirror", "mDelete", "mViewModeToggle",
  "toolSelect", "toolDraw", "toolNote", "toolMaskAdd", "toolCellEdit", "toolFlowEdit", "toolClusterEdit", "toolRigEdit", "lockAllToggle",
  "btnCopy", "btnCopyMirror", "btnDelete", "zoomIn", "zoomOut", "zoomReset", "zoomFit", "zoomLabel", "undoAction", "redoAction",
  "newProject", "saveProject", "saveProjectLink", "loadProject", "exportPng", "fileInput", "globalTextSize", "globalFont",
  "snapGrid", "snapObjects", "snapCenters", "snapGaps", "propName", "propTextSize", "propTextSizeLabel", "propX", "propY", "propRot",
  "propWm", "propHm", "propScale", "shapePointPanel", "propShapePointX", "propShapePointY", "propAreaM2", "propAreaM2Badge", "propColorA", "propColorB", "btnAutoContrast", "btnRandomColor",
  "propCellX", "propCellY", "propCellUnit", "propDataFlow", "propDataFlowZ", "propNumberCells",
  "splitVariantField", "splitVariantControl", "splitVariantManualBadge", "propSplitVariant", "propSplitVariantDec", "propSplitVariantInc",
  "propSplitVariantLabel", "btnClearMasks", "btnResetFlowLocks", "btnResetManualClusters", "btnConvertRegionsToScreens", "rectList",
  "specModePanel", "specAutoBlocks", "specModeClose"
];

export const createEditorDomRefs = (documentRef = document) => {
  const $ = id => documentRef.getElementById(id);
  const pickEls = ids => Object.fromEntries(ids.map(id => [id, $(id)]));
  const cv = $("editorCanvas");
  const wrap = $("canvasWrap");
  let overlayCanvas = $("editorOverlayCanvas");
  if (cv && cv.parentNode && !overlayCanvas) {
    overlayCanvas = documentRef.createElement("canvas");
    overlayCanvas.id = "editorOverlayCanvas";
    overlayCanvas.className = "editor-overlay-canvas";
    overlayCanvas.setAttribute("aria-hidden", "true");
    overlayCanvas.tabIndex = -1;
    cv.insertAdjacentElement("afterend", overlayCanvas);
  }
  const el = {
    ...pickEls(EDITOR_ELEMENT_IDS),
    toolbar: $("toolbarMain"),
    overflowToggle: $("toolbarOverflowToggle"),
    overflowPopup: $("toolbarOverflowPopup"),
    project: $("projectName"),
    save: $("saveProject"),
    saveLink: $("saveProjectLink"),
    load: $("loadProject"),
    exp: $("exportPng"),
    file: $("fileInput"),
    textSize: $("globalTextSize"),
    font: $("globalFont"),
    name: $("propName"),
    rectTextSize: $("propTextSize"),
    rectTextSizeLabel: $("propTextSizeLabel"),
    x: $("propX"),
    y: $("propY"),
    rot: $("propRot"),
    wm: $("propWm"),
    hm: $("propHm"),
    shapePointPanel: $("shapePointPanel"),
    shapePointX: $("propShapePointX"),
    shapePointY: $("propShapePointY"),
    scale: $("propScale"),
    areaM2: $("propAreaM2"),
    a: $("propColorA"),
    b: $("propColorB"),
    randColor: $("btnRandomColor"),
    cx: $("propCellX"),
    cy: $("propCellY"),
    cUnit: $("propCellUnit"),
    dataFlow: $("propDataFlow"),
    dataFlowZ: $("propDataFlowZ"),
    numCells: $("propNumberCells"),
    splitVariant: $("propSplitVariant"),
    splitVariantDec: $("propSplitVariantDec"),
    splitVariantInc: $("propSplitVariantInc"),
    splitVariantLabel: $("propSplitVariantLabel"),
    list: $("rectList"),
    mobileDock: documentRef.querySelector(".mobile-dock"),
    side: $("sidePanel"),
    undo: $("undoAction"),
    redo: $("redoAction"),
    newProject: $("newProject")
  };
  return {
    cv,
    ctx: cv.getContext("2d"),
    overlayCanvas,
    overlayCtx: overlayCanvas ? overlayCanvas.getContext("2d") : null,
    wrap,
    el,
    desktopToolButtons: [el.toolSelect, el.toolDraw, el.toolMaskAdd, el.toolCellEdit, el.toolFlowEdit, el.toolClusterEdit, el.toolRigEdit].filter(Boolean),
    mobileToolButtons: [el.mToolSelect, el.mToolDraw, el.mToolMaskAdd, el.mToolCellEdit, el.mToolFlowEdit, el.mToolClusterEdit, el.mToolRigEdit].filter(Boolean)
  };
};

export const createInitialEditorState = () => ({
  debugSnap: false,
  renderProfiler: false,
  renderProfile: null,
  rects: [],
  sel: null,
  selSet: new Set(),
  selMultiBase: null,
  mode: "select",
  createToolMode: "draw",
  viewMode: "art",
  camX: 0,
  camY: 0,
  zoom: 1,
  next: 1,
  draft: null,
  drag: null,
  selBox: null,
  flowDrag: null,
  manualFlowDrag: null,
  flowHover: null,
  flowDirHover: null,
  flowResetHover: null,
  flowRegionRid: null,
  flowEditVariant: "auto",
  flowEditPoints: [],
  flowStartHandles: [],
  flowDirButtons: [],
  flowResetButtons: [],
  flowLinkAnchors: [],
  flowLinkSegments: [],
  flowLinkHover: null,
  flowLinkPending: null,
  flowLinkDrag: null,
  flowLinks: [],
  clusterActiveId: null,
  clusterHandles: [],
  clusterHandleHover: null,
  clusterCellHover: null,
  clusterStartHover: null,
  clusterBorderHover: null,
  clusterDrag: null,
  rigHover: null,
  pan: false,
  panS: null,
  g: { x: null, y: null },
  dg: null,
  keys: { space: false, ctrl: false },
  clip: null,
  touch: null,
  textSize: 32,
  fontFamily: "Roboto",
  globalScale: 256,
  fontReady: false,
  projectName: "project",
  saveLocationId: "proj-project",
  themeMode: "auto",
  lockAll: false,
  installLayers: { text: true, flow: true, rig: true },
  specCustomText: "",
  specCustomSections: {},
  maskPath: [],
  maskHover: null,
  cellHover: null,
  cellHoverPos: null,
  tabs: [],
  activeTabId: null,
  nextTabId: 1,
  snap: { grid: false, objects: true, centers: true, gaps: true },
  history: { undo: [], redo: [], current: null, suspend: false }
});
